services:
  node-app:
    container_name: node
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: icey
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
